#!/usr/bin/env python3
"""Adversarial keystone test (referee specificity defense).

For each of the top-15 most-abundant network hubs (CSP1-2 + 14
alternatives), fit a single JSDM model on the joint top-40 + each
candidate, then compute the JSDM-knockout ΔShannon. Report ranked
results so we can show CSP1-2's effect sits in the upper tail of
the null distribution generated by 14 plausible alternative hubs.

Output:
  cache/jsdm_knockout_alternatives.tsv  — one row per candidate hub
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
CACHE = REPO / "cache"
sys.path.insert(0, str(REPO / "src"))

# ----------------------------------------------------------------------------
# Load amplicon data and metadata
# ----------------------------------------------------------------------------
ft = pd.read_parquet(CACHE / "feature_table.parquet")
tax = pd.read_parquet(CACHE / "taxonomy.parquet")
meta = pd.read_parquet(CACHE / "metadata_with_rainfall.parquet").set_index("sample")

if "genus" not in tax.columns and "Genus" in tax.columns:
    tax = tax.rename(columns={"Genus": "genus"})

# Compute per-sample Shannon
def _shannon(col):
    x = col[col > 0].astype(float)
    if x.empty:
        return float("nan")
    p = x / x.sum()
    return float(-(p * np.log(p)).sum())
meta["shannon"] = ft.apply(_shannon, axis=0).rename("shannon").reindex(meta.index)

# Build genus-level relative abundance
ft_rel = ft.div(ft.sum(axis=0), axis=1)
asv_to_genus = tax["genus"].reindex(ft.index).fillna("Unclassified")
genus_relab = (ft_rel.assign(genus=asv_to_genus.values)
               .groupby("genus").sum())

# Map "Dadabacteria" / "CSP1-2" — SILVA assigns CSP1-2 ASVs to either label
csp_asvs = tax[tax["Taxon"].str.contains("CSP1-2|Dadabacteria",
                                          case=False, regex=True, na=False)].index
meta["csp_relab"] = ft_rel.loc[csp_asvs].sum(axis=0).reindex(meta.index).fillna(0)

# Compartment numeric
comp_map = {"surface": 0, "deep": 1, "rhizosphere": 2}
meta["compartment_num"] = meta["compartment"].map(comp_map).astype(float)

# ----------------------------------------------------------------------------
# Pick candidate hub list
# ----------------------------------------------------------------------------
# Read the surface network nodes — top-15 hubs as candidates
nodes = pd.concat([
    pd.read_csv(CACHE / f"network_nodes_{c}.tsv", sep="\t").assign(comp=c)
    for c in ("surface", "deep", "rhizosphere")
], ignore_index=True)

# Average degree across compartments — picks consistent hubs
mean_deg = (nodes.groupby("node")["degree"]
            .mean().sort_values(ascending=False))
# Keep candidates that exist in genus_relab
candidates = []
for n in mean_deg.index:
    if n == "CSP1-2":
        continue  # add explicitly first below
    if n in genus_relab.index and len(candidates) < 14:
        candidates.append(n)
candidates = ["CSP1-2"] + candidates  # 15 total
print(f"Candidate hubs ({len(candidates)}):")
for c in candidates:
    print(f"  {c:25s}  mean_deg={mean_deg.get(c, 0):.1f}")

# ----------------------------------------------------------------------------
# Build response matrix Y[n, J]: candidates ∪ top-40 most-abundant genera
# ----------------------------------------------------------------------------
g_means = genus_relab.mean(axis=1).sort_values(ascending=False)
top40 = list(g_means.head(40).index)
genera = list(dict.fromkeys(candidates + top40))
print(f"\nResponse matrix: J = {len(genera)} genera")

Y_dict = {}
for g in genera:
    if g == "CSP1-2":
        Y_dict[g] = meta["csp_relab"]
    elif g in genus_relab.index:
        Y_dict[g] = genus_relab.loc[g].reindex(meta.index).fillna(0)
    else:
        Y_dict[g] = pd.Series(0.0, index=meta.index)
Ymat = pd.DataFrame({g: Y_dict[g] for g in genera})

Yl = np.log(Ymat.values + 1e-5)
X_env = meta[["rain_W30d", "temp_mean_W30d", "compartment_num"]].values.astype(float)
mm = np.all(np.isfinite(np.c_[Yl, X_env]), axis=1)
Yl, X_env = Yl[mm], X_env[mm]
Xz = (X_env - X_env.mean(0)) / X_env.std(0)
Y_mean, Y_std = Yl.mean(0), Yl.std(0)
Yz = (Yl - Y_mean) / Y_std
n, J = Yz.shape
K = 3
print(f"JSDM data: n={n} samples, J={J} genera, K={K} latent factors")

# ----------------------------------------------------------------------------
# Fit JSDM
# ----------------------------------------------------------------------------
import jax
import jax.numpy as jnp
import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS

def jsdm_model(X, Y, J, K):
    P = X.shape[1]
    beta = numpyro.sample("beta", dist.Normal(0, 1).expand([J, P]))
    Lambda = numpyro.sample("Lambda", dist.Normal(0, 0.5).expand([J, K]))
    sigma = numpyro.sample("sigma", dist.HalfNormal(1).expand([J]))
    eta = numpyro.sample("eta", dist.Normal(0, 1).expand([X.shape[0], K]))
    mu = X @ beta.T + eta @ Lambda.T
    with numpyro.plate("obs", X.shape[0], dim=-2):
        numpyro.sample("y", dist.Normal(mu, sigma), obs=Y)

print("Fitting JSDM ...")
kernel = NUTS(jsdm_model, target_accept_prob=0.8, max_tree_depth=7)
mcmc = MCMC(kernel, num_warmup=300, num_samples=400, num_chains=1,
            progress_bar=False)
mcmc.run(jax.random.PRNGKey(0), X=jnp.asarray(Xz),
         Y=jnp.asarray(Yz), J=J, K=K)
samples = {k: np.asarray(v) for k, v in mcmc.get_samples().items()}
beta_mean = samples["beta"].mean(0)
Lambda_mean = samples["Lambda"].mean(0)
sigma_mean = samples["sigma"].mean(0)
Sigma = Lambda_mean @ Lambda_mean.T + np.diag(sigma_mean ** 2)
print(f"  Σ shape = {Sigma.shape}")

# ----------------------------------------------------------------------------
# Knockout simulation per candidate
# ----------------------------------------------------------------------------
def shannon_rowwise(arr):
    p = arr / arr.sum(1, keepdims=True).clip(1e-10)
    return -(p * np.log(p.clip(1e-10))).sum(1)

def knockout_delta(target_idx):
    """ΔShannon per sample if target is dropped to its 2nd-percentile."""
    other_idx = [j for j in range(J) if j != target_idx]
    Sigma_oc = Sigma[other_idx, target_idx]
    Sigma_cc = Sigma[target_idx, target_idx]
    mu = Xz @ beta_mean.T
    mu_t = mu[:, target_idx]
    mu_o = mu[:, other_idx]

    def _predict(target_yz):
        adjust = (target_yz - mu_t)[:, None] * (Sigma_oc / Sigma_cc)[None, :]
        Y_pred = mu.copy()
        Y_pred[:, target_idx] = target_yz
        Y_pred[:, other_idx] = mu_o + adjust
        return Y_pred

    Y_base = _predict(Yz[:, target_idx])
    Y_ko = _predict(np.full(n, np.quantile(Yz[:, target_idx], 0.02)))
    Y_base_r = np.clip(np.exp(Y_base * Y_std + Y_mean) - 1e-5, 1e-10, None)
    Y_ko_r = np.clip(np.exp(Y_ko * Y_std + Y_mean) - 1e-5, 1e-10, None)
    Y_base_r /= Y_base_r.sum(1, keepdims=True)
    Y_ko_r /= Y_ko_r.sum(1, keepdims=True)
    delta = shannon_rowwise(Y_ko_r) - shannon_rowwise(Y_base_r)
    return delta

rows = []
for cand in candidates:
    if cand not in genera:
        continue
    j = genera.index(cand)
    delta = knockout_delta(j)
    rows.append({
        "candidate": cand,
        "is_csp": (cand == "CSP1-2"),
        "mean_degree": float(mean_deg.get(cand, 0)),
        "n_samples": int(n),
        "mean_delta_shannon": float(delta.mean()),
        "median_delta": float(np.median(delta)),
        "abs_mean_delta": float(np.abs(delta.mean())),
        "ci_lo_5": float(np.quantile(delta, 0.05)),
        "ci_hi_95": float(np.quantile(delta, 0.95)),
    })
    print(f"  {cand:25s}  Δ̄={delta.mean():+.3f}  "
          f"[5/95: {np.quantile(delta, 0.05):+.3f}, "
          f"{np.quantile(delta, 0.95):+.3f}]")

out = pd.DataFrame(rows).sort_values("abs_mean_delta", ascending=False)
out.to_csv(CACHE / "jsdm_knockout_alternatives.tsv", sep="\t", index=False)
print(f"\nwrote {CACHE / 'jsdm_knockout_alternatives.tsv'}")

# Specificity summary
ranks_by_abs = out.reset_index(drop=True)
csp_rank = (ranks_by_abs["candidate"] == "CSP1-2").idxmax() + 1
print(f"\nCSP1-2 rank by |ΔShannon|: {csp_rank} of {len(ranks_by_abs)}")
print("Top-5 by |ΔShannon|:")
for _, r in ranks_by_abs.head(5).iterrows():
    print(f"  {r['candidate']:22s}  Δ̄ = {r['mean_delta_shannon']:+.3f}")
