#!/usr/bin/env python3
"""Render the supplementary tables of the biology-context and trait-gene
modules as LaTeX (``generated/biology_context_tables.tex``).  Every number
comes from ``analysis/v3/biology_context/*.tsv`` and
``analysis/v3/trait_genes/*.tsv``; ``tests/test_biology_context.py`` re-renders
the fragment and requires it to match the committed copy.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
BIO = ROOT / "analysis/v3/biology_context"
TRAIT = ROOT / "analysis/v3/trait_genes"
LABEL = {"surface": "surface", "shallow_subsurface": "shallow-subsurface", "root_adjacent": "root-adjacent"}


def esc(text) -> str:
    # Brackets are braced so that a cell starting with "[" is not read as an
    # optional argument of the preceding row end.
    return (
        str(text).replace("&", r"\&").replace("%", r"\%").replace("_", r"\_").replace("#", r"\#")
        .replace("[", "{[}").replace("]", "{]}")
    )


def it(name) -> str:
    return r"\textit{" + esc(name) + "}"


def scientific(value: float, digits: int = 1, math_mode: bool = True) -> str:
    mantissa, exponent = f"{value:.{digits}e}".split("e")
    body = rf"{mantissa}\times10^{{{int(exponent)}}}"
    return f"${body}$" if math_mode else body


GENE_SYMBOLS = frozenset((
    "coxL", "hyaB", "hhyL", "hoxH", "rbcL", "cbbL", "psbA", "nifH",
    "amoA", "pmoA", "nirK", "nirS", "nosZ", "ureC", "otsA", "otsB",
    "treY", "treZ", "ectA", "ectB", "ectC", "crtB", "spo0A", "phrB",
    "uvrA", "recA", "katE", "katG", "sodA", "dps",
))


def marker_description(text: str) -> str:
    """Italicize explicit gene symbols; retain protein/product names in roman."""
    return re.sub(r"\b[A-Za-z][A-Za-z0-9]*\b",
                  lambda match: it(match[0]) if match[0] in GENE_SYMBOLS else match[0],
                  esc(text))


def positive_share(value: float) -> str:
    return r"$<0.01$" if 0 < value < 0.005 else f"{value:.2f}"


def table(caption: str, label: str, spec: str, header: str, rows: list[str], size: str = r"\footnotesize") -> str:
    return "\n".join(
        [r"\begin{table}[htbp]", r"\centering" + size, r"\caption{" + caption + "}", r"\label{" + label + "}",
         r"\begin{tabular}{" + spec + "}", r"\toprule", header + r" \\", r"\midrule", *rows, r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    )


HEADER = "% Generated by analysis/v3/render_biology_context_tex.py from analysis/v3/biology_context and\n% analysis/v3/trait_genes. Do not edit by hand.\n"


def render(bio_dir: Path = BIO, trait_dir: Path = TRAIT, ph_path: Path | None = None) -> tuple[str, str]:
    """Return (S5 fragment, S8 fragment)."""
    BIO, TRAIT = bio_dir, trait_dir
    parts = [HEADER]
    parts_s8 = [HEADER]

    alpha = pd.read_csv(BIO / "alpha_by_landform.tsv", sep="\t")
    def thirds(text):
        counts = dict(item.split(":") for item in text.split(","))
        return ", ".join(f"{counts[key]} {key}" for key in ("west", "central", "east") if key in counts)
    rows = [f"{esc(r.landform.replace('oilspill', 'oil spill'))} & {r.n_sites} & {esc(thirds(r.thirds))} & {r.mean_shannon:.2f} & {r.mean_expected_richness_25k:.0f} & {r.mean_normalized_evenness:.3f} \\\\" for r in alpha.itertuples()]
    p = alpha.iloc[0]
    parts.append(table(
        r"Field landform of the $60$ core sites and site-mean diversity by landform (site means of Shannon diversity, expected richness at $25{,}000$ reads and normalized Shannon diversity). Thirds are the western, central and eastern $20$ sites by route position. Mann-Whitney tests of dune against saline-pan sites gave"
        f" $p={p['dune_vs_pan_mannwhitney_p_shannon']:.2f}$, ${p['dune_vs_pan_mannwhitney_p_expected_richness_25k']:.2f}$ and ${p['dune_vs_pan_mannwhitney_p_normalized_evenness']:.2f}$ for the three measures.",
        "tab:landform-alpha", "lrP{3.7cm}rrr", r"Landform & Sites & Thirds & Shannon & Richness & Norm. Shannon", rows))

    omni = pd.read_csv(BIO / "landform_composition_omnibus.tsv", sep="\t")
    route = pd.read_csv(BIO / "route_model_dune_sensitivity.tsv", sep="\t")
    clim = pd.read_csv(BIO / "climate_diversity_dune_sensitivity.tsv", sep="\t")
    rows = [f"Dune vs saline pan, {esc({'none': 'unadjusted', 'route_linear_quadratic': 'route-adjusted'}.get(r.adjustment, r.adjustment.replace('_', ' ')))} & pseudo-$F={r.pseudo_f:.2f}$ & $p={r.permutation_p:.4f}$ \\\\" for r in omni.itertuples()]
    dune = route.iloc[-1]
    rows += [
        f"Route model, all $60$ sites & $R^2={route.iloc[0]['route_r2']:.3f}$ & \\\\",
        f"Route model, $44$ dune sites & $R^2={dune['route_r2']:.3f}$ & \\\\",
        f"Route genera at $q<0.05$ & {int(dune['supported_route_genera_all_sites'])} (all) / {int(dune['supported_route_genera_dune_sites'])} (dune) & {int(dune['supported_in_both_same_sign'])} in both, same sign \\\\",
    ]
    rows.append(r"\midrule Climate association & All $60$ sites & Dune $44$ sites \\")
    for r in clim.itertuples():
        climate = {'mean_air_temperature_c': 'Temperature', 'mean_monthly_rain_mm': 'Rain', 'mean_relative_humidity_pct': 'Humidity'}[r.climate_variable]
        metric = r.diversity_measure.replace('normalized_evenness', 'normalized Shannon').replace('expected_richness_25k', 'richness').replace('_', ' ').replace('shannon', 'Shannon')
        rows.append(f"{esc(climate)} vs {esc(metric)} & $\\rho={r.spearman_rho_all_60:.2f}$ ($q={scientific(r.q_bh_9_all_60, digits=2, math_mode=False)}$) & $\\rho={r.spearman_rho_dune_44:.2f}$ ($q={scientific(r.q_bh_9_dune_44, digits=2, math_mode=False)}$) \\\\")
    parts.append(table(
        r"Landform sensitivity of the geographic and climate results. The composition contrast between the $44$ dune and $9$ saline-pan sites uses the site-level CLR means of the route model, without and with adjustment for route position (linear plus quadratic), $9{,}999$ label permutations. The route model and the genus route correlations were refitted on dune sites only; the nine climate-diversity Spearman correlations are given for all $60$ sites and for the $44$ dune sites (Benjamini--Hochberg $q$ within each set of nine).",
        "tab:landform-sensitivity", "P{4.4cm}P{3.6cm}P{3.6cm}", r"Quantity & Estimate & Test or comparison", rows))

    fam = pd.read_csv(BIO / "compartment_genus_family.tsv", sep="\t")
    sup = fam[fam["supported_q_lt_0_05"]]
    rows = []
    for contrast in ("Deep-Surface", "Rhizosphere-Surface", "Rhizosphere-Deep"):
        block = sup[sup["contrast"] == contrast]
        first = LABEL[block["first_compartment"].iloc[0]]
        second = LABEL[block["second_compartment"].iloc[0]]
        for direction, sub in (("higher in " + first, block.sort_values("mean_clr_difference", ascending=False).head(8)), ("higher in " + second, block.sort_values("mean_clr_difference").head(8))):
            rows.append(r"\multicolumn{5}{l}{\emph{" + esc(f"{first} vs {second}: {direction}") + "}} \\\\")
            for r in sub.itertuples():
                rows.append(f"{it(r.genus)} & {esc(r.phylum)} & {r.mean_clr_difference:.2f} & [{r.ci_low:.2f}, {r.ci_high:.2f}] & {scientific(r.q_bh_600)} \\\\")
    parts.append(table(
        f"Genera carrying the compartment differences: the eight largest supported paired mean CLR differences per contrast and direction ({len(sup)} of $600$ tests at Benjamini--Hochberg $q<0.05$; site bootstrap $95\\,\\%$ interval; sign-flip $p$ over sites). The paired means reproduce the committed displacement loadings of Figure~2d.",
        "tab:compartment-genera", "llrlr", r"Genus & Phylum & $\Delta$ CLR & 95\,\% CI & $q$", rows, r"\scriptsize"))

    lead = pd.read_csv(BIO / "compartment_pathway_leaders.tsv", sep="\t")
    parts, parts_s5 = parts_s8, parts
    rows = []
    for (contrast, higher), block in lead.groupby(["contrast", "higher_in"], sort=False):
        rows.append(r"\multicolumn{3}{l}{\emph{" + esc(f"{contrast.replace('Deep', 'shallow-subsurface').replace('Rhizosphere', 'root-adjacent').replace('Surface', 'surface')}: higher in {LABEL[higher]}") + "}} \\\\")
        for r in block.head(5).itertuples():
            rows.append(f"{esc(r.pathway)} & {esc(r.description)} & {r.mean_clr_difference:.2f} \\\\")
    parts.append(table(
        r"Leading supported predicted-pathway contrasts per compartment pair and direction (five largest paired mean CLR differences among the $270$ supported tests of the $600$-test family).",
        "tab:compartment-pathways", "lP{7.0cm}r", r"Pathway & Description & $\Delta$ CLR", rows, r"\scriptsize"))

    parts = parts_s5
    xl = pd.read_csv(BIO / "xrf_axis_loadings.tsv", sep="\t")
    xg = pd.read_csv(BIO / "xrf_axis_genus_correlations.tsv", sep="\t")
    xs = xg[xg["supported_q_lt_0_05"]]
    rows = [r"\multicolumn{4}{l}{\emph{Element loadings of the laboratory-XRF axis}} \\"]
    rows += [f"{esc(r.element)} & & {r.pc1_loading:.3f} & \\\\" for r in xl.sort_values('pc1_loading', ascending=False).itertuples()]
    rows.append(r"\multicolumn{4}{l}{\emph{Genera increasing with the axis (Ca, Mg, Na, S, Cl, Fe, Ti side)}} \\")
    rows += [f"{it(r.genus)} & {esc(r.phylum)} & {r.spearman_rho_elemental_axis:.2f} & {scientific(r.q_bh_200)} \\\\" for r in xs.sort_values('spearman_rho_elemental_axis', ascending=False).head(10).itertuples()]
    rows.append(r"\multicolumn{4}{l}{\emph{Genera decreasing with the axis (Si side)}} \\")
    rows += [f"{it(r.genus)} & {esc(r.phylum)} & {r.spearman_rho_elemental_axis:.2f} & {scientific(r.q_bh_200)} \\\\" for r in xs.sort_values('spearman_rho_elemental_axis').head(10).itertuples()]
    parts.append(table(
        f"The laboratory-XRF elemental axis: element loadings of the first principal component after within-campaign standardization, and the genera whose site-level CLR values track the site-mean axis (Spearman over $60$ sites; {len(xs)} of $200$ genera at Benjamini--Hochberg $q<0.05$).",
        "tab:xrf-genera", "llrr", r"Element or genus & Phylum & Loading or $\rho$ & $q$", rows, r"\scriptsize"))

    pg = pd.read_csv(ph_path or BIO / "ph_genus_correlations.tsv", sep="\t")
    ps = pg[pg["supported_q_lt_0_05"]]
    rows = [r"\multicolumn{4}{l}{\emph{Increasing with site-mean pH}} \\"]
    rows += [f"{it(r.genus)} & {esc(r.phylum)} & {r.spearman_rho_site_ph:.2f} & {scientific(r.q_bh_200)} \\\\" for r in ps.sort_values('spearman_rho_site_ph', ascending=False).head(10).itertuples()]
    rows.append(r"\multicolumn{4}{l}{\emph{Decreasing with site-mean pH}} \\")
    rows += [f"{it(r.genus)} & {esc(r.phylum)} & {r.spearman_rho_site_ph:.2f} & {scientific(r.q_bh_200)} \\\\" for r in ps.sort_values('spearman_rho_site_ph').head(10).itertuples()]
    parts.append(table(
        f"Genera whose site-level CLR values track site-mean archived-soil pH. pH means give each campaign--site--compartment group equal weight within site ($563$ groups, $60$ sites; {len(ps)} of $200$ genera at Benjamini--Hochberg $q<0.05$, {int((ps['route_supported'].fillna(False)).sum())} of them also supported in the route family). These site-level Spearman tests retain spatial dependence among sites.",
        "tab:ph-genera", "llrr", r"Genus & Phylum & $\rho$ & $q$", rows, r"\scriptsize"))

    core = pd.read_csv(BIO / "core_genera_by_compartment.tsv", sep="\t")
    rows = [f"{LABEL[r.compartment]} & {r.n_sites_pooled} & {r.n_genera_detected_any_site} & {r.n_core_genera_ge_90pct_sites} & {r.median_rarefied_genera_per_site:.0f} & {r.mean_site_occupancy_of_detected_genera:.3f} \\\\" for r in core.itertuples()]
    parts.append(table(
        r"Genus occupancy per compartment after pooling campaigns within site and subsampling each site to $12{,}865$ reads ($20$ draws; detected when present in at least half of the draws). Core genera occur at $\geq 90\,\%$ of sites.",
        "tab:core-genera", "lrrrrr", r"Compartment & Sites & Genera detected & Core genera & Median genera per site & Mean occupancy", rows))

    parts = parts_s8
    gs = pd.read_csv(TRAIT / "genome_trait_summary.tsv", sep="\t")
    rows = [f"{marker_description(r.description)} & {esc(r.category)} & {100 * r.fraction_of_genomes:.1f} & {100 * r.mean_share_surface:.1f} & {100 * r.mean_share_shallow_subsurface:.1f} & {100 * r.mean_share_root_adjacent:.1f} & {esc(r.leading_carrier_phyla.split(';')[0] if isinstance(r.leading_carrier_phyla, str) and r.leading_carrier_phyla else '')} \\\\" for r in gs.itertuples()]
    parts.append(table(
        r"Trait genes in the $975$ annotated genomes of the companion shotgun catalogue (KO membership in \texttt{analysis/v3/trait\_genes/trait\_definitions.tsv}): fraction of genomes carrying at least one member KO, the abundance-weighted share of the recruited community carrying the trait in the $150$ shotgun libraries by compartment (surface $27$, shallow-subsurface $44$, root-adjacent $79$ libraries), and the leading carrier phylum with its genome count.",
        "tab:trait-genomes", "P{3.0cm}P{2.0cm}rrrrP{2.4cm}", r"Marker set & Category & Genomes (\%) & Surface & Shallow & Root-adj. & Leading carriers", rows, r"\scriptsize"))

    pc = pd.read_csv(TRAIT / "picrust_trait_summary.tsv", sep="\t")
    cc = pd.read_csv(TRAIT / "picrust_trait_compartment_contrasts.tsv", sep="\t")
    ag = pd.read_csv(TRAIT / "source_agreement.tsv", sep="\t").set_index("trait")
    descriptions = gs.set_index("trait")["description"].to_dict()
    rows = []
    for r in pc.itertuples():
        c = cc[cc["trait"] == r.trait].set_index("contrast")
        def fc(name):
            row = c.loc[name]
            return f"{row['fold_change']:.2f}" + (r"$^{*}$" if row["supported_q_lt_0_05"] else "")
        agree = ag.loc[r.trait, "spearman_rho_genome_vs_picrust"]
        rows.append(f"{marker_description(descriptions[r.trait])} & {positive_share(1e4 * r.mean_predicted_share_surface)} & {positive_share(1e4 * r.mean_predicted_share_shallow_subsurface)} & {positive_share(1e4 * r.mean_predicted_share_root_adjacent)} & {fc('shallow_subsurface-surface')} & {fc('root_adjacent-surface')} & {fc('root_adjacent-shallow_subsurface')} & {r.spearman_rho_route:+.2f}{'$^{*}$' if r.q_bh_route < 0.05 else ''} & {agree:+.2f} \\\\")
    parts.append(table(
        r"PICRUSt2 predicted trait-gene share of KO abundance ($\times 10^{4}$) by compartment; paired site-level fold changes between compartments (sign-flip tests, Benjamini--Hochberg over $60$ tests; $^{*}$ $q<0.05$); Spearman correlation of site means with route position ($^{*}$ $q<0.05$ over $20$ tests); and the Spearman agreement between the genome-derived and predicted shares in the $119$ matched shotgun libraries.",
        "tab:trait-picrust", "P{4.0cm}rrrrrrrr", r"Marker set & Surface & Shallow & Root & Sh/Su & Ro/Su & Ro/Sh & Route $\rho$ & Agreement", rows, r"\scriptsize"))
    return "\n".join(parts_s5), "\n".join(parts_s8)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "empty-quarter-amplicon/generated/biology_context_tables.tex")
    parser.add_argument("--output-traits", type=Path, default=ROOT / "empty-quarter-amplicon/generated/trait_gene_tables.tex")
    parser.add_argument("--biology-dir", type=Path, default=BIO)
    parser.add_argument("--trait-dir", type=Path, default=TRAIT)
    parser.add_argument("--ph-correlations", type=Path)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    s5, s8 = render(args.biology_dir, args.trait_dir, args.ph_correlations)
    args.output.write_text(s5, encoding="utf-8")
    args.output_traits.write_text(s8, encoding="utf-8")
    sources = sorted(set(args.biology_dir.glob("*.tsv")) | set(args.trait_dir.glob("*.tsv")))
    if args.ph_correlations:
        sources.append(args.ph_correlations)
    def digest(path):
        return hashlib.sha256(path.read_bytes()).hexdigest()
    manifest = {"generator": {"path": str(Path(__file__).resolve()), "sha256": digest(Path(__file__))},
                "inputs": [{"path": str(p.resolve()), "sha256": digest(p)} for p in sources],
                "outputs": [{"path": str(p.resolve()), "sha256": digest(p)} for p in (args.output, args.output_traits)]}
    args.output.with_suffix(".manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(args.output)
    print(args.output_traits)


if __name__ == "__main__":
    main()
