#!/usr/bin/env python3
"""Render matched-campaign contrasts from the common-profile sensitivity."""
import argparse
import hashlib
import json
from pathlib import Path

import pandas as pd


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", type=Path, default=Path(__file__).parent / "paired_alpha_sensitivity_20260909/paired_alpha_estimands.tsv")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    frame = pd.read_csv(args.results, sep="\t")
    rows = frame[frame.cohort.eq("common_profiles") & frame.estimand.eq("campaign_matched")]
    if len(rows) != 9 or set(rows.n_sites) != {60}:
        raise ValueError("Expected nine common-profile contrasts over 60 sites")
    metrics = {"shannon": "Shannon diversity", "richness_rare": "Expected richness", "normalized_shannon": "Normalized Shannon diversity"}
    contrasts = {"Deep-Surface": "Shallow minus surface", "Rhizosphere-Surface": "Root-adjacent minus surface", "Rhizosphere-Deep": "Root-adjacent minus shallow"}
    lines = [r"% Generated by analysis/v3/render_paired_alpha_sensitivity.py.",
             r"\begin{table}[htbp]\centering\footnotesize",
             r"\caption{Campaign-matched differences using profiles with all three diversity endpoints. Each contrast averages paired campaign differences within site, then averages over 60 sites. Intervals are percentile 95\% site-bootstrap intervals from 1,000,000 draws (seed 20260723). Signed-rank $q$ values correct three contrasts within each endpoint.}",
             r"\label{tab:matched-alpha}",
             r"\begin{tabular}{P{2.5cm}P{3.9cm}rP{3.7cm}r}\toprule",
             r"Endpoint & Contrast & Blocks & Mean [95\% interval] & $q$ \\\midrule"]
    for row in rows.itertuples():
        digits = 1 if row.metric == "richness_rare" else (4 if row.metric == "normalized_shannon" else 3)
        q = f"{row.q_three_contrasts:.3g}"
        if "e" in q:
            coefficient, exponent = q.split("e")
            q = rf"{coefficient}\times10^{{{int(exponent)}}}"
        lines.append(f"{metrics[row.metric]} & {contrasts[row.contrast]} & {int(row.n_campaign_site_pairs)} & "
                     f"${row.mean:.{digits}f}$ [${row.ci_low:.{digits}f}$, ${row.ci_high:.{digits}f}$] & ${q}$ " + r"\\")
    lines += [r"\bottomrule\end{tabular}\end{table}"]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
    manifest = {"source": str(args.results), "source_sha256": hashlib.sha256(args.results.read_bytes()).hexdigest(),
                "generator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
                "output_sha256": hashlib.sha256(args.output.read_bytes()).hexdigest()}
    args.output.with_suffix(".manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    main()
