#!/usr/bin/env python3
"""Render the refitted rainfall analysis; use the pinned manuscript environment."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def render(source, paper):
    summary = json.loads((source / "summary.json").read_text())
    boot = pd.read_csv(source / "refitted_site_bootstrap.tsv.gz", sep="\t")
    ranges = pd.read_csv(source / "refitted_site_bootstrap_summary.tsv", sep="\t")
    orbit = pd.read_csv(source / "calendar_year_orbit.tsv", sep="\t")
    products = [("nasa_power", "NASA POWER", "#176b87"), ("open_meteo", "Open-Meteo", "#b76332")]
    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 9,
                         "axes.titlesize": 10, "axes.labelsize": 9,
                         "xtick.labelsize": 9, "ytick.labelsize": 9,
                         "legend.fontsize": 9, "pdf.fonttype": 42,
                         "axes.spines.top": False, "axes.spines.right": False})
    fig, axes = plt.subplots(1, 3, figsize=(6.7, 3.2), layout="constrained")
    days = np.linspace(.01, 15, 500)
    for key, name, colour in products:
        fit = summary["observed"][key]
        peak = fit["peak_days"]
        curve = fit["beta"] * (days / peak) * np.exp(1 - days / peak)
        axes[0].plot(days, curve, color=colour, lw=1.8, label=name)
        axes[0].scatter([peak], [fit["beta"]], color=colour, s=20, zorder=3)
        freq = boot.loc[boot["product"] == key, "fixed_endpoint_selected_peak_days"].value_counts(normalize=True).sort_index()
        axes[1].plot(freq.index, freq.values * 100, color=colour, lw=1.6, marker=".", ms=4)
    axes[0].set(xlim=(0, 15), ylim=(0, 355), xlabel="Complete days before collection",
                ylabel="Expected taxa per mm", title="a   Selected richness\ncurves")
    axes[0].set_xticks([0, 5, 10, 15])
    axes[0].legend(frameon=False, loc="upper right")
    axes[1].set(xlim=(0, 30), xlabel="Reselected peak (days)",
                ylabel="Whole-site refits (%)", title="b   Peak selection\nin 9,999 refits")
    values = orbit["joint_positive_max"].to_numpy()
    colours = ["#9c2933"] + ["#818b93"] * (len(values) - 1)
    axes[2].scatter(np.arange(len(values)), values, c=colours, s=35, zorder=3)
    axes[2].axhline(values[0], color="#9c2933", lw=.8, ls="--")
    axes[2].set_xticks(np.arange(len(values)), ["1", "2", "3", "4", "5", "6"])
    axes[2].set(ylim=(0, .23), ylabel="Maximum positive\npartial correlation",
                xlabel="Year assignment", title="c   Calendar-year\nassignments")
    axes[2].text(.97, .12, "p = 2/6", transform=axes[2].transAxes,
                 ha="right", color="#9c2933", fontsize=9)
    for ax in axes:
        ax.grid(axis="y", color="#e6e8ea", lw=.6)
        ax.set_axisbelow(True)
    figure = paper / "figures/rain_calendar_refit.pdf"
    figure.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(figure, metadata={"CreationDate": None, "ModDate": None})
    plt.close(fig)

    def interval(product, quantity, digits):
        row = ranges.loc[(ranges["product"] == product) & (ranges["quantity"] == quantity)].iloc[0]
        return f"[{row.lower_2_5:.{digits}f},{row.upper_97_5:.{digits}f}]"

    lines = [r"% Generated by render_rain_calendar_refit.py; values from the complete raw-site refit.",
             r"\begin{table}[H]\centering\small",
             r"\caption{Rainfall associations and central $95\,\%$ ranges across $9{,}999$ whole-site refits. Every draw refits the nuisance model. Effect and partial-$R^2$ ranges retain the observed richness peak; timing ranges reselect that peak. Endpoint selection searches all three diversity measures and all $60$ peaks separately within each product.}",
             r"\label{tab:rain-pulse-uncertainty}",
             r"\begin{tabular}{P{2cm}P{3cm}P{3cm}P{2.5cm}P{2cm}}\toprule",
             r"Product & Taxa per mm [range] & Partial $R^2$ [range] & Peak, days [range] & Richness selected \\\midrule"]
    for key, name, _ in products:
        fit = summary["observed"][key]
        fraction = summary["bootstrap_endpoint_frequencies"][key]["richness_hurlbert_25000"]
        lines.append(f"{name} & ${fit['beta']:.1f}$ ${interval(key, 'fixed_beta', 1)}$ & "
                     f"${fit['partial_r2']:.4f}$ ${interval(key, 'fixed_partial_r2', 4)}$ & "
                     f"${fit['peak_days']:.1f}$ ${interval(key, 'fixed_endpoint_selected_peak_days', 1)}$ & "
                     f"${fraction * 100:.1f}\\,\\%$ " + r"\\")
    lines += [r"\bottomrule\end{tabular}\end{table}",
              r"\begin{table}[H]\centering\small",
              r"\caption{Complete calendar-year permutation search. Each row maps the original rainfall years $(2023,2024,2025)$ to the listed years for both products and all sites. Entries are the largest positive partial correlation across $60$ peaks and three endpoints. The observed assignment is the first row.}",
              r"\label{tab:rain-calendar-orbit}",
              r"\begin{tabular}{lrrr}\toprule",
              r"Assigned years & NASA POWER & Open-Meteo & Joint maximum \\\midrule"]
    for row in orbit.itertuples():
        mapping = json.loads(row.year_mapping)
        years = ", ".join(str(mapping[str(y)]) for y in (2023, 2024, 2025))
        lines.append(f"{years} & ${row.nasa_power_positive_max:.4f}$ & ${row.open_meteo_positive_max:.4f}$ & ${row.joint_positive_max:.4f}$ " + r"\\")
    lines += [r"\bottomrule\end{tabular}\end{table}", ""]
    table = paper / "generated/rain_calendar_refit_tables.tex"
    table.parent.mkdir(parents=True, exist_ok=True)
    table.write_text("\n".join(lines))
    inputs = [source / name for name in ("summary.json", "refitted_site_bootstrap.tsv.gz",
              "refitted_site_bootstrap_summary.tsv", "calendar_year_orbit.tsv", "manifest.json")]
    inputs.append(Path(__file__).resolve())
    manifest = {"inputs": [{"path": str(p.resolve()), "sha256": sha(p)} for p in inputs],
                "outputs": {str(p.relative_to(paper)): sha(p) for p in (figure, table)},
                "software": {"matplotlib": matplotlib.__version__, "freetype": matplotlib.ft2font.__freetype_version__,
                             "numpy": np.__version__, "pandas": pd.__version__}}
    (table.with_suffix(".manifest.json")).write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--paper", type=Path, required=True)
    args = parser.parse_args()
    render(args.source.resolve(), args.paper.resolve())
