#!/usr/bin/env python3
"""Render every covariance-model probability and the spatial null calibration."""
import argparse
import hashlib
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
LABELS = {"exponential": "Exponential", "matern_3_2": r"Mat\'ern $3/2$", "matern_5_2": r"Mat\'ern $5/2$"}
CASES = {
    "iid_sites": "Independent sites",
    "group_noise_only": "Independent group noise",
    "matched_exp_medium": "Exponential, $203$ km, $50\\,\\%$ noise",
    "matched_matern_smooth": r"Mat\'ern $3/2$, $507$ km, $10\,\%$ noise",
    "off_grid_range_noise": "Off-grid range and noise fraction",
    "nonstationary_site_field": "Nonstationary spatial field",
    "nonseparable_two_site_fields": "Different spatial fields by response",
    "heavy_tailed_group_innovations": "Heavy-tailed group noise",
}


def render(results: Path):
    tests = pd.read_csv(results / "spatial_covariance_tests.tsv", sep="\t")
    calibration = pd.read_csv(results / "null_calibration.tsv", sep="\t")
    lines = [r"% Generated by analysis/v3/render_spatial_covariance_tex.py.",
             r"\begin{table}[htbp]\centering\small",
             r"\caption{Route rotation probabilities under the complete geometry-defined covariance family. Range is the kernel scale in kilometres; the four columns give the group-noise fraction of mean marginal site variance after centring and averaging. Each model uses $9{,}999$ rotations and a plus-one probability. The independent-site reference and propagated group-noise-only model both give $p=0.0001$. Monte Carlo tail intervals and covariance condition numbers are in the source TSV.}",
             r"\label{tab:spatial-covariance}",
             r"\begin{tabular}{llrrrr}\toprule",
             r"Kernel & Range (km) & $1\,\%$ & $10\,\%$ & $50\,\%$ & $90\,\%$ \\\midrule"]
    for kind, label in LABELS.items():
        selected = tests[tests.kernel == kind]
        for index, (length, group) in enumerate(selected.groupby("range_km", sort=True)):
            probabilities = group.set_index("group_noise_fraction").rotation_p
            cells = " & ".join(f"${probabilities.loc[f]:.4f}$" for f in (.01, .1, .5, .9))
            lines.append(f"{label if index == 0 else ''} & ${length:.1f}$ & {cells} " + r"\\")
        lines.append(r"\addlinespace")
    lines += [r"\bottomrule\end{tabular}\end{table}", "",
              r"\begin{table}[htbp]\centering\footnotesize",
              r"\caption{Spatial-null calibration on the observed site geometry and group coverage. Each cell is the rejection percentage at $p\leq0.05$ and its exact binomial $95\,\%$ interval from $500$ simulated datasets, with $199$ rotations or site permutations per dataset. The generating-covariance test uses the known Gaussian simulation covariance. The nonseparable case has response-specific row covariances; the Gaussian reference is omitted for heavy-tailed innovations. The family maximum is the largest probability across all $73$ propagated covariance models.}",
              r"\label{tab:spatial-calibration}",
              r"\begin{tabular}{P{4.4cm}P{2.6cm}P{2.6cm}P{2.6cm}}\toprule",
              r"Generating null & Site permutation & Generating covariance & Family maximum \\\midrule"]
    for case, label in CASES.items():
        part = calibration[calibration.null_case == case].set_index("method")
        cells = []
        for method in ("unrestricted_site_permutation", "generating_covariance_rotation", "finite_family_maximum"):
            if method not in part.index:
                cells.append("Not evaluated")
            else:
                row = part.loc[method]
                cells.append(f"${100*row.rejection_fraction:.1f}$ [${100*row.binomial_ci_low:.1f}$, ${100*row.binomial_ci_high:.1f}$]")
        lines.append(label + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule\end{tabular}\end{table}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", type=Path, default=ROOT / "analysis/v3/spatial_covariance_sensitivity_20260909")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.results))
    inputs = [args.results / name for name in ("spatial_covariance_tests.tsv", "null_calibration.tsv", "frozen_design.json", "frozen_design_addendum.json")]
    def digest(path):
        return hashlib.sha256(path.read_bytes()).hexdigest()
    manifest = {"generator": {"path": str(Path(__file__).resolve()), "sha256": digest(Path(__file__))},
                "inputs": [{"path": str(p.resolve()), "sha256": digest(p)} for p in inputs],
                "output": {"path": str(args.output.resolve()), "sha256": digest(args.output)}}
    args.output.with_suffix(".manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    main()
